#pragma once

namespace Redneck
{
	enum ExpressionType
	{
		//EXPRESSION_NUMBER,
		EXPRESSION_VALUE,
		EXPRESSION_BIN_OPERATION,
		EXPRESSION_IDENTIFIER,
		EXPRESSION_DECLARATION,
		EXPRESSION_IF,
		EXPRESSION_ASSOCIATION,
		EXPRESSION_ARGUMENT,
		EXPRESSION_FUNCTION,
		EXPRESSION_WHILE
	};
}