#pragma once

namespace Redneck
{
	enum TokenType
	{
		TOKEN_INT,
		TOKEN_STRING,
		TOKEN_IDENTIFIER,
		TOKEN_VARIABLE,
		TOKEN_IF,
		TOKEN_FUNC,
		TOKEN_COMMA,
		TOKEN_SEMI,
	//	TOKEN_LPAREN,
	//	TOKEN_RPAREN,
		TOKEN_LBRACKET,
		TOKEN_RBRACKET,
		TOKEN_LBRACE,
		TOKEN_RBRACE,
		TOKEN_ASSIGN,
		TOKEN_PLUS,
		TOKEN_MINUS,
		TOKEN_MULT,
		TOKEN_DIV,
		TOKEN_EQUALS,
		TOKEN_NULL,
		TOKEN_WHILE,
		TOKEN_GREATER,
		TOKEN_LESS
	};
}